### ISSUE TITLE
Not including alias on some links

### ISSUE THREAD

**Issue by EarthToMooney** [mnaoumov/obsidian-smart-rename#5] opened 2023-09-12 20:17 UTC
For example, I have a file named "D&D.md" in my Non-Work/Social folder. The only link to it is in Non-Work/Life & Philosophy/Parenting.md, in the line "- Tabletop games like [[D&D]] offer great social outlets also at low prices." 
I smart rename "D&D.md" to "Dungeons and Dragons.md" and the line becomes
"- Tabletop games like [[Dungeons and Dragons]] offer great social outlets also at low prices."
instead of what I expected, which would be 
"- Tabletop games like [[Dungeons and Dragons|D&D]] offer great social outlets also at low prices."
Not sure why this is.

**Comment by EarthToMooney** [comment] 2023-09-12 20:27
If I had to take a guess as to what's going wrong, I'd assume it may have something to do with the context these links appear in, not non-alphabetical characters and how the plugin handles them. Plenty of notes I've tried that have only letters and spaces work just fine, though some named that way also only work as expected when smart renaming for a fraction of all links using them.

**Comment by mnaoumov** [comment] 2023-09-13 19:38
@EarthToMooney thanks for your report, however I could not reproduce the issue

I prepared a vault for you double check

[vault.zip](https://github.com/mnaoumov/obsidian-smart-rename/files/12601307/vault.zip)

**Comment by ianlhayes** [comment] 2023-10-23 18:52
I came here because I was experiencing the same issue (only my filenames didn't have ampersands,) but the issue was resolved by relaunching Obsidian. It's unclear what was causing the issue, but given that I have other plugins, CSS snippets, etc. installed, it's likely not isolated to this plugin.

**Comment by mnaoumov** [comment] 2024-11-05 18:44
Fixed in https://github.com/mnaoumov/obsidian-smart-rename/releases/tag/2.0.0

**Closed by mnaoumov** 2024-11-05 18:44 UTC
